create table pais(
	codigo char(2),
	nombre varchar(50),
	primary key (codigo)
)

create table usuario(
	id_usuario int generated by default as identity (start with 1),	
	username varchar(20), 
	password varchar(20), 
	nombre varchar(50),
	pais char(2),
	primary key (id_usuario),
	foreign key (pais) references pais(codigo),
	unique (username)
);

create table rol(
	id_rol int generated by default as identity (start with 1),	
	nombre varchar(50), 
	descripcion varchar(100),
	primary key (id_rol),
	unique (nombre)
);

create table usuario_rol (
	id_usuario int, 
	id_rol int, 
	primary key(id_usuario, id_rol), 
	foreign key (id_usuario) references usuario(id_usuario), 
	foreign key (id_rol) references rol(id_rol)
);